### ISSUE TITLE
ConcurrentQueue not a FIFO

### ISSUE THREAD

**Issue by jtgoral** [cameron314/concurrentqueue#52] opened 2016-06-08 01:57 UTC
I was using the queue in my logger and noticed that the timestamps are out of order.
Both blocking and non-blocking have the same problem. The SafeQueue which can be found on Github is a FIFO and passes the same test.

I am using GCC-4.9.1 on CentOS 6.5.

This is a test (I replaced my timestmped messages with just integers:

``` C++
//#include "blockingconcurrentqueue.h"
#include "concurrentqueue.h"
//#include "SafeQueue.hpp"
#include <vector>
#include <future>
#include <mutex>
#include <functional>
#include <iostream>
#include <unistd.h>
#include <atomic>

constexpr unsigned threadCnt = 10;
std::mutex              mtx, inmtx;                   // for queue_
std::condition_variable cv;                    // for queue_
using QueData = std::vector<std::int64_t>;
QueData in, out;
std::atomic<int> nta{0};
using Queue = moodycamel::ConcurrentQueue<std::int64_t>; // errors
//using Queue = moodycamel::BlockingConcurrentQueue<std::int64_t>;//errors
using Queue =SafeQueue<std::int64_t>; // no errors

auto generateData (Queue& q)-> void
{
    int nt = std::atomic_fetch_add(&nta, 1);
    std::cout << "thread "<< nt <<" started "<< std::endl;
    std::int64_t  n = 10000;
    while ( n > -2)
    {
                // serialize enqueueing
                std::unique_lock<std::mutex> lk(inmtx);
                auto k = n;
                in.push_back(k); // sent data to compare
                q.enqueue(std::move(k));
                cv.notify_one();
                --n;
    }
    std::cout << "thread "<< nt <<" finished with n="<< n+1 <<std::endl;
}
int main()
{
    Queue queue;
    std::vector<std::future<void>> tasks;                 // thread pool
    tasks.emplace_back(std::async(std::launch::async,[&]()
    {
                std::int64_t ncount{};
                std::cout << "dequeueing thread started "<< std::endl;
                while(ncount<threadCnt)
                {
                    //std::cout << "reading dequeued item"<< std::endl;
                    std::int64_t item;
                    if(queue.try_dequeue(item)) // get of the queue
                    {
                                if( -1 == item )
                                {
                                    ncount++;
                                    std::cout << "received -1 in dequeueing thread"<< ncount << std::endl;
                                }
                                out.push_back(item); // received data to compare
                    }
                    else
                    {
                               //wait for signal or timeout
                                std::unique_lock<std::mutex> lk(mtx);
                                cv.wait_for(lk, std::chrono::milliseconds(100));
                    }
                }
                std::cout << "dequeueing thread finished "<< std::endl;
    }));
    usleep(1000*100);// for reader to start
    for(int n = 0; n<threadCnt; ++n )
    {
                tasks.emplace_back(std::async(std::launch::async,[&]()
                {
                    generateData(queue);
                }));
    }
    // wait for all threads to finish
    for( auto& t : tasks) t.get();
    std::cout << "all threads finished "<< std::endl;
    // compare results
    assert (in.size() == out.size());
    std::cout << "comparing "<<  in.size() << "items" << std::endl;
    unsigned errCnt{};
    for (int n =0 ; n < in.size(); ++n)
    {
                if(in[n] != out[n])
                {
                    //std::cout << "item " << n <<" " << in[n] << " != " << out[n] << std::endl;
                    ++errCnt;
                }
    }
    std::cout << "done: error count=" << errCnt << std::endl;
    return 0;
}
```

**Comment by cameron314** [comment] 2016-06-08 02:02
This is by design, sorry. It's well documented in the README. Elements enqueued on the same thread (or using the same producer token) are FIFO, but that's the only guarantee.

I created issue #6 to add a feature to support this sort of synchronization, but it won't happen anytime soon, I'm afraid.

**Comment by jtgoral** [comment] 2016-06-08 02:29
You are saying that ConcurrentQueue is not a queue? Per Wikipedia definition: https://en.wikipedia.org/wiki/Queue_(abstract_data_type)

**Comment by cameron314** [comment] 2016-06-08 02:40
It's a set of sub-queues (one per thread/producer token) that are polled independently. It turns out that most of the time this is all that's needed (with logging being one of the more notable exceptions, though even then it's not always needed).

When I was designing it, it didn't occur to me that separate threads may be synchronizing their accesses to the queue outside of the queue itself. Unfortunately this is not something that can be easily changed; the queue would need to be redesigned almost from scratch (which is basically what issue #6 is about -- adding another queue implementation wrapped in the same API).

**Comment by jtgoral** [comment] 2016-06-08 02:58
Imagine you were flying from Chicago to LA. You lined up in the queue, where in the front of it it was your turn next. The TSA clerk said "Next please" and you started  to move. He said "Not you, the person behind you". And you thought you were standing in the queue:-)

**Comment by cameron314** [comment] 2016-06-08 03:08
No, that can't happen. Imagine you're in line at the airport and there's six lines in front of four booths. One of the booths becomes free. Who's next? Whichever of the people at the front of one of the lines advances first.

**Comment by jtgoral** [comment] 2016-06-08 03:21
I never saw more lines than booths. I saw priority lines, for flying personnel for example, but it is OK, there is a concept of a priority queue. Random queue is something new I have to learn to live with:-)

**Comment by cameron314** [comment] 2016-06-08 03:30
All right, well, I've never actually been to an airport :-)
But the analogy still holds -- people are coming in from multiple entrances at the same time. What's to say there can't be more than one (equal-priority) line at each entrance, with a different agent handling each line? Surely that's more efficient than trying to get everyone into a single line, even if there's the same number of agents dealing with them.

Anyway, even with a fully-linearizeable queue your timestamps/integer IDs could end up out of order. It's less likely, but still entirely possible (probable, even, under contention over a reasonable period of time) -- since the queue itself doesn't know about your timestamps, there's a race between when the element A is put in on a given thread and the element B is put in on another thread. B would have to not only be generated after A, but also *after A had been fully enqueued*. This is rather tricky to synchronize (the simple sledgehammer approach, of course, is just to use a mutex, but that kinda defeats the purpose).

Off to bed, goodnight for now.

**Comment by llvilanova** [comment] 2016-07-07 13:47
Silly comment, but many USA immigration checks on airports *do* end up with more queues than booths (e.g., NYC); then you have some clerks scheduling which top-of-a-queue goes to what free booth.

**Comment by cameron314** [comment] 2017-01-18 17:40
Closing for now, as this is by design, unfortunate though it may be for some use cases. If I ever implement another queue, I'll try to keep a global total order to cut down on many headaches.

**Closed by cameron314** 2017-01-18 17:40 UTC
