### ISSUE TITLE
Fuzz tests on Android fail

### ISSUE THREAD

**Issue by sonicdebris** [cameron314/concurrentqueue#42] opened 2016-03-17 16:04 UTC
Hi, I'm evaluating the concurrentqueue for use on android, in a c++ app.

I tried running the fuzz tests (well, basically a chopped down version of the main in fuzztests.cpp), and some of them failed. It happens in two different points of the same type of test (core_thread_local). Here's some data, grouped by type of error:

```
AFTER 672 ITERATIONS
 multithread_produce: 232 successful, 0 failed
 multithread_consume: 240 successful, 0 failed
 multithread_produce_and_consume: 192 successful, 0 failed
 completely_random: 208 successful, 0 failed
 core_add_only_list: 252 successful, 0 failed
 core_thread_local: 197 successful, 14 failed
 - Executed 1335 tests so far

Reason: assertion failed on line 593: p->value == 0
 Seed: d7990b4e4dea1895
 Seed: 96fe1c7d0392537b
 Seed: 139af5f3d1c7e4bb
 Seed: d013a74b4faa2d1b
 Seed: 7b0ceb690c3286d9
 Seed: 955a9db3764ac57b
 Seed: 09efdf685ad77030

Reason: assertion failed on line 611: *localData[i] == i
 Seed: 3eab167012cb7d8c
 Seed: c448fd7c0b9725fc
 Seed: 4e5b54df425bbbb6
 Seed: 639d2c83865d2b47
 Seed: f9ae9a0365bec08c
 Seed: c3bd84c3c96e2f17
 Seed: 6de7a43c21a7bd6e
```

I'm not sure how to interpret these results yet, I will try having a closer look at the code, in the meanwhile I thought it wouldn't hurt to ask and share what I got. Any pointer would be much appreciated, thanks!

As a reference, here's the test function I "assembled":

```
bool FuzzyTestMoodyCamelConcurrentQueue()
{
    uint32_t iteration = 0;
    uint64_t seed = 0;
    int result = 0;
    test_type test;
    const char* failReason;

    while (true)
    {
        seed = (static_cast<uint64_t>(std::time(NULL)) << 32) | iteration++;
        // MurmurHash3 64-bit finalizer
        seed ^= seed >> 33;
        seed *= 0xff51afd7ed558ccd;
        seed ^= seed >> 33;
        seed *= 0xc4ceb9fe1a85ec53;

        g_seed.store(seed, std::memory_order_release);
        int result;

        try {
            result = run_test(seed, 2, test, failReason);
        }
        catch (std::exception const& e) {

            PRINTMSG("*** Exception : %s\n      Seed: %08x%08x\n      Test: %s\n\n", e.what(), (uint32_t)(seed >> 32), (uint32_t)(seed), test_names[test]);
            return false;
        }
        catch (...) {

            PRINTMSG("*** Unknown exception thrown!\n      Seed: %08x%08x\n      Test: %s\n\n", (uint32_t)(seed >> 32), (uint32_t)(seed), test_names[test]);
            return false;
        }

        if (!result) {
            result = 1;
            PRINTMSG("*** Failure detected!\n      Seed: %08x%08x\n      Test: %s\n      Reason: %s\n", (uint32_t)(seed >> 32), (uint32_t)(seed), test_names[test], failReason);
        }

        if ((iteration & 15) == 0) {

            std::uint64_t total = 0;
            PRINTMSG("AFTER %u ITERATIONS",iteration);
            for (int i = 0; i != TEST_TYPE_COUNT; ++i)
            {
                PRINTMSG(" %s: %llu successful, %llu failed\n", test_names[i], (unsigned long long)(test_count[i] - fail_count[i]), (unsigned long long)fail_count[i]);
                total += test_count[i];
            }
            PRINTMSG(" - Executed %llu tests so far", (unsigned long long)total);
        }
    }
}
```

where PRINTMSG is a macro defined to the android native log function.

**Comment by cameron314** [comment] 2016-03-17 17:16
Ahhh, that's not good! Thanks for reporting this.

Do you think you could try getting the unit tests to run? They might be a little easier to investigate (but still very hard).

If you comment out the `if` at [line 241](https://github.com/cameron314/concurrentqueue/blob/master/tests/corealgos.h#L241) of corealgos.h, does the fuzz test start passing?

**Comment by sonicdebris** [comment] 2016-03-17 18:22
I commented the `if (hash != mainHash)` block, but still I got a failure:

```
AFTER 64 ITERATIONS
  multithread_produce: 24 successful, 0 failed
  multithread_consume: 18 successful, 0 failed
  multithread_produce_and_consume: 26 successful, 0 failed
  completely_random: 20 successful, 0 failed
  core_add_only_list: 24 successful, 0 failed
  core_thread_local: 15 successful, 1 failed
  - Executed 128 tests so far
```
I'm trying to build the unit tests, but I noticed a note about thread_local not being supported on iOS/ARM.
I am building for arm devices, might this be related?

I will be back with the unit tests results as soon as I make them run.

**Comment by cameron314** [comment] 2016-03-17 18:26
Right, `thread_local` is not supported on ARM, but it is carefully not used by the queue itself in those cases. The tests are supposed to compile as well (I merged a pull request from someone who got them to compile for iOS).

Since it still fails without the `if`, the bug is more fundamental to the algorithm itself. Rats. I'll need to have a closer look. But basically, the bug is somewhere in `get_or_create()` in corealgos.h (or the test itself, but the test looks correct). Could also be the compiler or even hardware, but we can't assume that from the start.

Thanks for taking the time to run the tests! Very much appreciated.

**Comment by cameron314** [comment] 2016-03-17 18:28
Oh, and because this is confusing, note that `thread_local` (the keyword) and the `ThreadLocal` (class) test are completely independent of each other. The queue depends on the latter all the time, but the former only on some OSes with x86.

**Comment by sonicdebris** [comment] 2016-03-17 19:08
Yes, sorry, I had a look at the code and MOODYCAMEL_CPP11_THREAD_LOCAL_SUPPORTED is in fact not defined.

I run the unit tests, 50 iterations: all passed.

As a reference, the function I used, again a stripped down version of the unit tests main() :
```
bool MoodycamelLockfreeQueueTests()
{
	unsigned int iterations = 100;
	ConcurrentQueueTests tests;
	bool result;
	PRINTMSG(">-> Running %d iterations of all unit tests for moodycamel::ConcurrentQueue.\n",iterations);
	result = tests.run(iterations);
	if (result)
		PRINTMSG(">-> All tests passed.\n");
	else
		PRINTMSG(">-> Some Tests failed!\n");
	return result;
}
```

**Comment by cameron314** [comment] 2016-03-17 19:15
Very interesting. The same code is tested by the unit tests. Maybe try running just the `core_thread_local` test with a high number of iterations? (I think there's an overload of `run` that takes the name of a test.)

Your cut down wrappers look fine, by the way.

**Comment by cameron314** [comment] 2016-03-17 19:16
...of course, at that point, the unit tests mostly become fuzz tests. It's hard to test non-determinacy :-)

**Comment by sonicdebris** [comment] 2016-03-18 11:10
I've run the `core_thread_local` test twice, with 1000 and 5000 iterations, with no errors.
If it can help, I could prepare and share a small android test project.

**Comment by cameron314** [comment] 2016-03-18 14:58
Sure! Everything helps. I've never developed for android, though -- does this reproduce in a simulator?

**Comment by sonicdebris** [comment] 2016-03-18 15:02
I reproduced it only on real devices (my app doesn't run on emulators). Once I set up the project I will check. It may take a little while, though.

**Comment by cameron314** [comment] 2016-03-18 15:06
No worries. Bugs like this aren't really fixed by stepping through with a debugger anyway. It's mostly scrutinizing the code. But being able to reproduce something helps a lot, because you can play with the code until something interesting pops out.

**Comment by AstralStorm** [comment] 2016-06-06 09:43
Possibly related: Android GCC 4.9 for ARM mentions an issue with one compare and exchange operation unless I enable the workaround for Apple. It is probably an issue in GCC on ARM in general.
It is possible that older GCC (4.8) just ignored the problem.

In the code below, EventStruct contains std::function and some flags. We're using try_enqueue and try_dequeue with a statically sized queue. The application is built with -std=c++11.

Specifically, unless line 99 workaround, the error is:
ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/atomic_base.h: In member function 'moodycamel::ConcurrentQueue<T, Traits>::ImplicitProducer* moodycamel::ConcurrentQueue<T, Traits>::get_or_add_implicit_producer() [with T = EventStruct; Traits = moodycamel::ConcurrentQueueDefaultTraits]':
ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/atomic_base.h:581:70: error: failure memory model cannot be stronger than success memory model for '__atomic_compare_exchange'
  return __atomic_compare_exchange_n(&_M_i, &__i1, __i2, 0, __m1, __m2);
                                                                      ^
ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/atomic_base.h:581:70: error: failure memory model cannot be stronger than success memory model for '__atomic_compare_exchange'

**Comment by cameron314** [comment] 2016-06-06 16:53
Hmm. I don't understand how that compiler error could be produced, since `get_or_add_implicit_producer` only ever passes a single memory order to the `compare_exchange_*` methods (i.e. the success and failure orders are always the same strength). Is there more context to that error message? Like a line number in concurrentqueue.h? And the function that calls `compare_exchange_strong` in atomic_base.h?

I think I might understand the problem, though. It seems that `thread_local` may not be properly supported on ARM with g++, not just with iOS. I had assumed that since it compiled, it must be supported, but perhaps that's not the case. Enabling the iOS workaround for other platforms will not cause incorrect results, but may result in performance degradation. (If performance matters, use tokens!)

I'll add a patch for disabling use of `thread_local` on ARM regardless of the platform (basically what you did by hand).

**Comment by cameron314** [comment] 2016-06-06 17:09
I'd really appreciate it if someone could try running the fuzztests again with the latest version.

**Closed** 2019-12-28 01:59 UTC
Labels: bug
