### ISSUE TITLE
Errors/Warnings during compilation of tests on OrangePI/armv71

### ISSUE THREAD

**Issue by tysonite** [cameron314/concurrentqueue#185] opened 2020-02-04 07:51 UTC
Linux: `Linux orangepione 4.13.15-sunxi #1 SMP Tue Nov 21 23:35:46 MSK 2017 armv7l armv7l armv7l GNU/Linux`

GCC:
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/5/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --disable-werror --enable-multilib --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.12)
```

Output of `make`:
```
orangepi@orangepione:~/concurrentqueue/build$ make
test -d bin || mkdir bin
g++ -std=c++11 -Wall -pedantic-errors -Wpedantic -Wconversion -pthread  -g -O0    -fno-elide-constructors ../tests/common/simplethread.cpp ../tests/common/sy                                 stemtime.cpp ../tests/unittests/unittests.cpp -o bin/unittests -lrt
In file included from ../tests/unittests/../../blockingconcurrentqueue.h:10:0,
                 from ../tests/unittests/unittests.cpp:32:
../tests/unittests/../../lightweightsemaphore.h: In member function ‘bool moodycamel::details::Semaphore::timed_wait(uint64_t)’:
../tests/unittests/../../lightweightsemaphore.h:213:13: warning: conversion to ‘__time_t {aka long int}’ from ‘uint64_t {aka long long unsigned int}’ may alt                                 er its value [-Wconversion]
   ts.tv_sec += usecs / usecs_in_1_sec;
             ^
../tests/unittests/../../lightweightsemaphore.h:214:14: warning: conversion to ‘__syscall_slong_t {aka long int}’ from ‘uint64_t {aka long long unsigned int}                                 ’ may alter its value [-Wconversion]
   ts.tv_nsec += (usecs % usecs_in_1_sec) * 1000;
              ^
../tests/unittests/unittests.cpp: At global scope:
../tests/unittests/unittests.cpp:271:32: error: requested alignment 128 is larger than 64 [-Wattributes]
 struct MOODYCAMEL_ALIGNAS(128) VeryAligned {
                                ^
../tests/unittests/unittests.cpp: In instantiation of ‘bool moodycamel::ConcurrentQueueTests::full_api() [with Traits = moodycamel::ConcurrentQueueDefaultTra                                 its]’:
../tests/unittests/unittests.cpp:335:3:   required from here
../tests/unittests/unittests.cpp:3623:9: warning: unused variable ‘lockFree’ [-Wunused-variable]
    bool lockFree = ConcurrentQueue<Foo, Traits>::is_lock_free();
         ^
../tests/unittests/unittests.cpp: In instantiation of ‘bool moodycamel::ConcurrentQueueTests::full_api() [with Traits = moodycamel::SmallIndexTraits]’:
../tests/unittests/unittests.cpp:336:3:   required from here
../tests/unittests/unittests.cpp:3623:9: warning: unused variable ‘lockFree’ [-Wunused-variable]
makefile:33: recipe for target 'bin/unittests' failed
make: *** [bin/unittests] Error 1
```

**Comment by cameron314** [comment] 2020-02-05 02:28
Hopefully fixed. If you could verify that would be appreciated.

**Comment by tysonite** [comment] 2020-02-05 07:24
Unittests have been compiled without warnings/errors now on OrangePI/armv7 (32 bit). They have also passed.

I would need to check on RaspberryPI (arm 64 bit), I don't have access to this device now, can do it later today/tomorrow. 

BTW, it looks like fuzztests leak memory. This process have been killed on that iteration by Linux oom killer on OrangePI (512 Mb RAM):
```
Executed 6912 tests so far:
    multithread_produce: 1176 successful, 0 failed
    multithread_consume: 1160 successful, 0 failed
    multithread_produce_and_consume: 1162 successful, 0 failed
    completely_random: 1180 successful, 0 failed
    core_add_only_list: 1088 successful, 0 failed
    core_thread_local: 1146 successful, 0 failed
```

```
[1296085.640985] Out of memory: Kill process 9883 (fuzztests) score 570 or sacrifice child
[1296085.641002] Killed process 9883 (fuzztests) total-vm:549196kB, anon-rss:220164kB, file-rss:56kB, shmem-rss:0kB
```

**Comment by tysonite** [comment] 2020-02-05 14:49
On RaspberryPI looks to be good as well.

**Comment by cameron314** [comment] 2020-02-09 18:01
I cannot reproduce the memory leak with the fuzztests.
Memory usage regularly spikes to >400 MB and drops to <20 MB.

Looking at the code, there's a comment `Note: If you're wondering where all the memory goes, it's mostly here!` above a vector with a worst-case size of 500000*32*2 ints, or ~128 MB. There's additionally quite a bit of memory allocated for the various enqueuing producer threads in the worst case.

Maybe try increasing your swap space, or reduce the constants of 500000 in the fuzztests source.

**Comment by cameron314** [comment] 2020-04-04 02:50
Closing for now, the original issue of warnings is resolved and the memory leak I can't reproduce. Feel free to open a new issue as required.

**Closed by cameron314** 2020-04-04 02:50 UTC
