### ISSUE TITLE
try_enqueue failed when size_approx() is already 0

### ISSUE THREAD

**Issue by 0x1997** [cameron314/concurrentqueue#55] opened 2016-08-02 12:58 UTC
There are N > 1 producers and one consumer. When shutting down the application, the last remaining producer sometimes loops infinitely while the consumer is still waiting for new items and `channel.size_approx()` also returns 0.

``` cpp
while (!channel.try_enqueue(producer_token, item))
{
  LOG(INFO) << "try_enqueue() failed, queue_size: " << channel.size_approx();
  usleep(wait_us);
}
// signal the consumer
```

**Comment by 0x1997** [comment] 2016-08-09 07:03
```cpp
#include <stdio.h>
#include <unistd.h>

#include <atomic>

#include <blockingconcurrentqueue.h>

using namespace moodycamel;
using Queue = ConcurrentQueue<size_t>;
using Semaphore = details::mpmc_sema::LightweightSemaphore;

struct Context
{
    std::atomic<bool> stop;
    Queue queue;
    Semaphore sema;

    Context() : stop(false), queue(64), sema(0) {}
};


void* produce(void* arg)
{
    Context* ctx = static_cast<Context*>(arg);
    ProducerToken token(ctx->queue);
    size_t id = static_cast<size_t>(pthread_self());

    while (!ctx->stop.load(std::memory_order_acquire))
    {
        while (!ctx->queue.try_enqueue(token, id))
        {
            printf("p: %lu failed: size=%lu\n", id, ctx->queue.size_approx());
            usleep(500000);
        }
        ctx->sema.signal();
    }

    printf("p=%lu stopped\n", id);
    return nullptr;
}

void* consume(void* arg)
{
    Context* ctx = static_cast<Context*>(arg);
    ConsumerToken token(ctx->queue);
    constexpr size_t BATCH_SIZE = 128;
    size_t batch[BATCH_SIZE];

    while (true)
    {
        for (size_t batch_size, count = 0, max = ctx->sema.waitMany(BATCH_SIZE);
             count != max; count += batch_size)
        {
            bool stop = ctx->stop.load(std::memory_order_acquire);
            batch_size = ctx->queue.try_dequeue_bulk(token, batch, max - count);
            if (stop && !batch_size)
                return nullptr;

            printf("c: dequeued %lu, remains %lu\n", batch_size, ctx->queue.size_approx());
            sleep(2);
        }
    }
}

int main()
{
    Context ctx;
    
    pthread_t consumer;
    pthread_create(&consumer, nullptr, consume, &ctx);

    constexpr size_t n = 2;
    pthread_t producers[n];
    for (size_t i = 0; i < n; ++i)
        pthread_create(&producers[i], nullptr, produce, &ctx);

    sleep(10);
    printf("shutting down\n");
    ctx.stop.store(true, std::memory_order_release);
    ctx.sema.signal(1);

    for (size_t i = 0; i < n; ++i)
        pthread_join(producers[i], nullptr);
    pthread_join(consumer, nullptr);
}
```

```shell
>> g++ -std=gnu++14 -g -pthread test.cc -o test && ./test
p: 139808548771584 failed: size=63
c: dequeued 1, remains 10
p: 139808557164288 failed: size=63
p: 139808557164288 failed: size=63
p: 139808548771584 failed: size=63
p: 139808557164288 failed: size=63
p: 139808548771584 failed: size=63
p: 139808548771584 failed: size=63
p: 139808557164288 failed: size=63
c: dequeued 63, remains 0
p: 139808557164288 failed: size=0
p: 139808548771584 failed: size=64
p: 139808557164288 failed: size=64
p: 139808548771584 failed: size=64
p: 139808548771584 failed: size=64
p: 139808557164288 failed: size=64
p: 139808548771584 failed: size=64
p: 139808557164288 failed: size=64
c: dequeued 64, remains 0
p: 139808557164288 failed: size=24
p: 139808548771584 failed: size=64
p: 139808548771584 failed: size=64
p: 139808557164288 failed: size=64
p: 139808548771584 failed: size=64
p: 139808557164288 failed: size=64
p: 139808548771584 failed: size=64
p: 139808557164288 failed: size=64
c: dequeued 64, remains 0
p: 139808557164288 failed: size=0
p: 139808548771584 failed: size=64
p: 139808557164288 failed: size=64
p: 139808548771584 failed: size=64
p: 139808548771584 failed: size=64
p: 139808557164288 failed: size=64
p: 139808548771584 failed: size=64
p: 139808557164288 failed: size=64
c: dequeued 64, remains 0
p: 139808557164288 failed: size=0
p: 139808548771584 failed: size=64
p: 139808548771584 failed: size=64
p: 139808557164288 failed: size=64
p: 139808548771584 failed: size=64
p: 139808557164288 failed: size=64
p: 139808557164288 failed: size=64
p: 139808548771584 failed: size=64
shutting down
c: dequeued 64, remains 0
p=139808548771584 stopped
p: 139808557164288 failed: size=1
p: 139808557164288 failed: size=1
p: 139808557164288 failed: size=1
p: 139808557164288 failed: size=1
c: dequeued 1, remains 0
p: 139808557164288 failed: size=0
p: 139808557164288 failed: size=0
```

**Comment by 0x1997** [comment] 2016-08-09 07:11
```cpp
#include <stdio.h>
#include <unistd.h>

#include <atomic>

#include <blockingconcurrentqueue.h>

using namespace moodycamel;
using Queue = ConcurrentQueue<size_t>;
using Semaphore = details::mpmc_sema::LightweightSemaphore;

struct Context
{
    std::atomic<bool> stop;
    Queue queue;
    Semaphore sema;

    Context() : stop(false), queue(64), sema(0) {}
};


void* produce(void* arg)
{
    Context* ctx = static_cast<Context*>(arg);
    ProducerToken token(ctx->queue);
    size_t id = static_cast<size_t>(pthread_self());

    while (!ctx->stop.load(std::memory_order_acquire))
    {
        while (!ctx->queue.try_enqueue(token, id))
        {
            printf("p: %lu failed: size=%lu\n", id, ctx->queue.size_approx());
            usleep(500000);
        }
        ctx->sema.signal();
    }

    printf("p=%lu stopped\n", id);
    return nullptr;
}

void* consume(void* arg)
{
    Context* ctx = static_cast<Context*>(arg);
    ConsumerToken token(ctx->queue);
    constexpr size_t BATCH_SIZE = 128;
    size_t batch[BATCH_SIZE];

    while (true)
    {
        for (size_t batch_size, count = 0, max = ctx->sema.waitMany(BATCH_SIZE);
             count != max; count += batch_size)
        {
            bool stop = ctx->stop.load(std::memory_order_acquire);
            batch_size = ctx->queue.try_dequeue_bulk(token, batch, max - count);
            if (stop && !batch_size)
                return nullptr;

            printf("c: dequeued %lu, remains %lu\n", batch_size, ctx->queue.size_approx());
            sleep(2);
        }
    }
}

int main()
{
    Context ctx;
    
    pthread_t consumer;
    pthread_create(&consumer, nullptr, consume, &ctx);

    constexpr size_t n = 2;
    pthread_t producers[n];
    for (size_t i = 0; i < n; ++i)
        pthread_create(&producers[i], nullptr, produce, &ctx);

    sleep(10);
    printf("shutting down\n");
    ctx.stop.store(true, std::memory_order_release);
    ctx.sema.signal(1);

    for (size_t i = 0; i < n; ++i)
        pthread_join(producers[i], nullptr);
    pthread_join(consumer, nullptr);
}
```

```shell
>> g++ -std=c++14 -g -pthread test.cc -o test && ./test
c: dequeued 32, remains 20
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
p: 140108574893824 failed: size=64
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
p: 140108583286528 failed: size=64
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
c: dequeued 64, remains 0
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
c: dequeued 64, remains 0
p: 140108574893824 failed: size=0
p: 140108583286528 failed: size=64
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
p: 140108574893824 failed: size=64
p: 140108583286528 failed: size=64
c: dequeued 64, remains 0
p: 140108574893824 failed: size=0
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
p: 140108583286528 failed: size=64
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
c: dequeued 64, remains 0
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
p: 140108583286528 failed: size=64
p: 140108574893824 failed: size=64
shutting down
c: dequeued 64, remains 0
p=140108583286528 stopped
p: 140108574893824 failed: size=1
p: 140108574893824 failed: size=1
p: 140108574893824 failed: size=1
p: 140108574893824 failed: size=1
c: dequeued 1, remains 0
p: 140108574893824 failed: size=0
p: 140108574893824 failed: size=0
p: 140108574893824 failed: size=0
# most of the time this loops infinitely
```

**Comment by cameron314** [comment] 2016-08-09 14:42
Awesome, thanks! I'll have a look on my lunch break.

**Comment by cameron314** [comment] 2016-08-09 20:08
Interesting, you're using the semaphore directly instead of the blocking version of the queue. Is there a particular reason? (Just curious.)

I think I see the problem. Your producer can get stuck in an infinite loop if the consumer exits prematurely. The consumer can exit as soon as `exit` is set and `try_dequeue_bulk` returns 0. However, `try_dequeue_bulk` is not guaranteed to immediately return `>0` when the queue contains an element, even with your semaphore synchronization. If you look at the implementation of the blocking version of the queue you'll see there's a loop after the semaphore wait for this very reason.

I'm sure you want to know why `try_dequeue_bulk` behaves this way, and frankly I can't remember. I'll look into it a bit further for you because I'm curious too. But it all comes back to the queue being non-linearizable and only eventually consistent. If I were to redo the queue, I would change this because the weak guarantees I give are helpful for performance but seem to bite almost everyone (including me) who uses the queue. Sorry!

**Comment by cameron314** [comment] 2016-08-09 20:09
...it also might be something else, that doesn't account for `size_approx()` returning 0. I'll have to look into this more tomorrow.

**Comment by 0x1997** [comment] 2016-08-10 06:23
I need direct access to the semaphore to wake up the consumer when all producers have stopped. Another option is to enqueue a sentinel value at the end, but I'm actually using a different semaphore implementation which spins directly on the counter inside `sem_t`.

I've updated the snippet to stop the MPSC pipeline in two steps. The problem remains.
```cpp
#include <stdio.h>
#include <unistd.h>

#include <atomic>

#include <blockingconcurrentqueue.h>

using namespace moodycamel;
using Queue = ConcurrentQueue<size_t>;
using Semaphore = details::mpmc_sema::LightweightSemaphore;

struct Context
{
    std::atomic<bool> stop_producer;
    std::atomic<bool> stop_consumer;
    Queue queue;
    Semaphore sema;

    Context() : stop_producer(false), stop_consumer(false), queue(64), sema(0) {}
};


void* produce(void* arg)
{
    Context* ctx = static_cast<Context*>(arg);
    ProducerToken token(ctx->queue);
    size_t id = static_cast<size_t>(pthread_self());

    while (!ctx->stop_producer.load(std::memory_order_acquire))
    {
        while (!ctx->queue.try_enqueue(token, id))
        {
            printf("p: %lu failed: size=%lu\n", id, ctx->queue.size_approx());
            usleep(500000);
        }
        ctx->sema.signal();
    }

    printf("p=%lu stopped\n", id);
    return nullptr;
}

void* consume(void* arg)
{
    Context* ctx = static_cast<Context*>(arg);
    ConsumerToken token(ctx->queue);
    constexpr size_t BATCH_SIZE = 128;
    size_t batch[BATCH_SIZE];

    while (true)
    {
        bool stop = ctx->stop_consumer.load(std::memory_order_acquire);
        for (size_t batch_size, count = 0, max = ctx->sema.waitMany(BATCH_SIZE);
             count != max; count += batch_size)
        {
            size_t to_dequeue = max - count;
            if (stop && to_dequeue == 1)
                goto EXIT;
            batch_size = ctx->queue.try_dequeue_bulk(token, batch, to_dequeue);

            printf("c: dequeued %lu, remains %lu\n", batch_size, ctx->queue.size_approx());
            sleep(2);
        }
    }

EXIT:
    printf("c stopped\n");
    return nullptr;
}

int main()
{
    Context ctx;
    
    pthread_t consumer;
    pthread_create(&consumer, nullptr, consume, &ctx);

    constexpr size_t n = 2;
    pthread_t producers[n];
    for (size_t i = 0; i < n; ++i)
        pthread_create(&producers[i], nullptr, produce, &ctx);

    sleep(10);
    printf("shutting down\n");
    ctx.stop_producer.store(true, std::memory_order_release);

    for (size_t i = 0; i < n; ++i)
        pthread_join(producers[i], nullptr);
    
    ctx.sema.signal();
    ctx.stop_consumer.store(true, std::memory_order_release);
    pthread_join(consumer, nullptr);
}
```

**Comment by 0x1997** [comment] 2016-08-10 10:29
I need direct access to the semaphore to wake up the consumer when all producers have stopped. Another option is to enqueue a sentinel value at the end, but I'm actually using a different semaphore implementation which spins directly on the counter inside `sem_t`.

I've updated the snippet to stop the MPSC pipeline in two steps and fixed a synchronization bug in the consumer. The problem remains.
```cpp
#include <stdio.h>
#include <unistd.h>

#include <atomic>

#include <blockingconcurrentqueue.h>

using namespace moodycamel;
using Queue = ConcurrentQueue<size_t>;
using Semaphore = details::mpmc_sema::LightweightSemaphore;

struct Context
{
    std::atomic<bool> stop_producer;
    std::atomic<bool> stop_consumer;
    Queue queue;
    Semaphore sema;

    Context() : stop_producer(false), stop_consumer(false), queue(64), sema(0) {}
};


void* produce(void* arg)
{
    Context* ctx = static_cast<Context*>(arg);
    ProducerToken token(ctx->queue);
    size_t id = static_cast<size_t>(pthread_self());

    while (!ctx->stop_producer.load(std::memory_order_acquire))
    {
        while (!ctx->queue.try_enqueue(token, id))
        {
            printf("p: %lu failed: size=%lu\n", id, ctx->queue.size_approx());
            usleep(500000);
        }
        ctx->sema.signal();
    }

    printf("p=%lu stopped\n", id);
    return nullptr;
}

void* consume(void* arg)
{
    Context* ctx = static_cast<Context*>(arg);
    ConsumerToken token(ctx->queue);
    constexpr size_t BATCH_SIZE = 128;
    size_t batch[BATCH_SIZE];

    while (true)
    {
        for (size_t batch_size, count = 0, max = ctx->sema.waitMany(BATCH_SIZE);
             count != max; count += batch_size)
        { 
            bool stop = ctx->stop_consumer.load(std::memory_order_acquire);
            size_t to_dequeue = max - count;
            batch_size = ctx->queue.try_dequeue_bulk(token, batch, to_dequeue);
            if (stop && !ctx->sema.tryWaitMany(1) && to_dequeue == 1 && !batch_size)
                goto EXIT;

            printf("c: dequeued %lu, remains %lu\n", batch_size, ctx->queue.size_approx());
            sleep(2);
        }
    }

EXIT:
    printf("c stopped\n");
    return nullptr;
}

int main()
{
    Context ctx;
    
    pthread_t consumer;
    pthread_create(&consumer, nullptr, consume, &ctx);

    constexpr size_t n = 2;
    pthread_t producers[n];
    for (size_t i = 0; i < n; ++i)
        pthread_create(&producers[i], nullptr, produce, &ctx);

    sleep(10);
    printf("shutting down\n");
    ctx.stop_producer.store(true, std::memory_order_release);

    for (size_t i = 0; i < n; ++i)
        pthread_join(producers[i], nullptr);
    
    ctx.sema.signal();
    ctx.stop_consumer.store(true, std::memory_order_release);
    pthread_join(consumer, nullptr);
}
```

**Comment by cameron314** [comment] 2016-08-10 17:51
Alright, your test case has uncovered multiple bugs (some small, some alarming). I need more time to look into this but it's a priority at this point. I'll update here when I figure out exactly what's going wrong (I know why the producer is starving forever (that part's not a bug as it stands), but the fix for it doesn't work (which *is* a bug), and there's other serious problems I noticed along the way too...).

Anyway, good test case! Thanks :-)

**Comment by ZizhengTai** [comment] 2016-12-17 11:19
Any updates / discoveries / fixes? :D

**Comment by ZizhengTai** [comment] 2016-12-19 12:38
@cameron314 Could you perhaps describe some of the "serious problems" you've found? We are using your queue in production code and would like to know if there is any mine field that we should avoid.

**Comment by cameron314** [comment] 2016-12-20 17:34
Sorry for the delay. I wandered off into other things. Yes, I will come back to this issue soon, likely in a couple weeks. The more serious issues seem to be related to the semaphore (so, only the blocking version is affected as far as I can tell so far), but there was also a bug in the constructor overload that caused the wrong amount of memory to be allocated.

With the code as it stands, it's normal that a producer can starve since the queue is only initialized with space for 64 elements, and a single producer may require all that space to itself; since these are explicit producers (with tokens), their memory is never recycled and the other producer can starve as a result (explicit producers hold onto their acquired blocks forever, even after the token is destroyed; a subsequent producer token will however reuse a disposed producer, so the memory isn't exactly lost, it's just not returned to the global pool for general use). I should change this too so that when an explicit producer is destroyed its blocks are released back to the central pool should another already-allocated producer require them.

**Comment by cameron314** [comment] 2019-12-28 01:55
I think the semaphore issues have been fixed.

It turns out to be very difficult to free a producer's blocks to the central pool when its token is destroyed, since the blocks may still contain elements that have not been dequeued yet. Adding logic to free the blocks as they are emptied would greatly impact the performance of the general case, and is tricky to do besides.

So, I'm going to close this issue for now.

**Closed by cameron314** 2019-12-28 01:55 UTC
